-- V16: Fix password_hash for all users.
--
-- The BCrypt hash seeded in V15 was generated offline and, while
-- structurally valid, did not actually match the literal string
-- "password" when verified by the running app's BCryptPasswordEncoder.
-- This migration replaces every user's hash with a freshly-generated
-- one that has been confirmed to match "password" in the target
-- runtime environment.
--
-- The hash below was generated by:
--   new BCryptPasswordEncoder(10).encode("password")
-- and verified with:
--   encoder.matches("password", hash) == true

UPDATE sys_user SET password_hash = '$2a$10$Qv64smtHKzHmsvja1SzSU.XkY0Y8D7Ffq85plN.oeVGyCJrKm3kCW';